### ISSUE TITLE
inconsistency evaluation results

### ISSUE THREAD

**Issue by shuangao** [triagemd/keras-eval#62]
I noticed that the evaluation results may be different when using the [keras_eval.utils.ensemble_model](https://github.com/triagemd/keras-eval/blob/master/keras_eval/utils.py#L253-L275) to manually ensemble different models. Here is an example

## Model to ensemble (arithmetric)

- [`Inception_v3`](https://lab.triage.com/models/n-way/snapshots/108)
- [`Inception_v4`](https://lab.triage.com/models/n-way/snapshots/109)
- [`Resnet_152`](https://lab.triage.com/models/n-way/snapshots/110)
- [`Densenet_201`](https://lab.triage.com/models/n-way/snapshots/111)

### On keras_eval

   f1_score | precision | top_1 | top_2 | top_3 | top_4 | top_5|
-- | -- | -- | -- | -- | -- | -- 
0.520981 | 0.64068 | 0.505455 | 0.643636 | 0.729091 | 0.772727 | 0.805454

### On Lab eval

[eval](https://lab.triage.com/models/skin-tone/evaluations/282)

@jsalbert

**Comment by jsalbert** [comment]
I tested ensembling directly and compared with ensembling using the function. Here is the [evaluation](https://drive.google.com/drive/u/2/folders/0B7Ni8-g0c6zqNENici0taDNQSDQ) in the cats vs dogs dataset, that is where we test the functions contained in `keras-eval`. I'll add a test in the next PR. 

I also tried it with multiple models and another set of data and there was a slight difference but very small (+-0.05 absolute performance). Probably due how to keras layers are doing the merge. 

If you use 4 models that are trained with different input shape, it is normal that you can see changes in the output because in the evaluation they all share the same input.
@shuangao  If there is a difference with the lab performance, maybe the best would be you to compute the results in your machine, so we can know if there is a bug in the function or in the lab.
